theme = "dario"
baseURL = "https://ianwattsweddingvideo.com/"
languageCode = 'en-us'
title = 'ian watts wedding video • tasmania'

[menu]

  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "videos"
    url = "/videos/"
    weight = 2

  [[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 4